import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Mono } from "next/font/google";
import { satoshi } from './fonts';
import "./globals.css";
import Navbar from "../../components/navbar";
import Footer from "../../components/footer";
import { FooterBackgroundProvider } from "../../context/FooterBackgroundContext";
import { ThemeProvider } from '../../context/ThemeContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceMono.variable} ${satoshi.variable} antialiased`}
      >
        <ThemeProvider>
        <FooterBackgroundProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </FooterBackgroundProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}